/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    All: typeof import('./src/components/all.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    DailyFinance: typeof import('./src/components/DailyFinance.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FinanceStates: typeof import('./src/components/FinanceStates.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PeriodStates: typeof import('./src/components/PeriodStates.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableRow: typeof import('./src/components/TableRow.vue')['default']
    WeightStates: typeof import('./src/components/WeightStates.vue')['default']
  }
}
